services:
  - type: web
    name: book-classification
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn book_classify.wsgi:application --bind 0.0.0.0:$PORT
