# Generated by Django 5.2 on 2025-04-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookprediction',
            old_name='genre',
            new_name='predicted_genre',
        ),
        migrations.AddField(
            model_name='bookprediction',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
