# Generated by Django 5.2 on 2025-04-14 08:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_genre_bookprediction_predicted_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookprediction',
            name='file_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bookprediction',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bookprediction',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
